### ISSUE TITLE
카테고리 이미지를 어떻게 가져올까요.

### ISSUE THREAD

**Issue by Taeila92** [LM-TeamProject/travel-here#18]
이것저것 생각해보고 하는중인데.

어떻게 가져와야 할지 잘 모르겠네요.
category스토어에서

다른 스토어로 데이터를 전달할수있나요??
아시는분 답변 부탁드려요.

**Comment by Elli-Jeon** [comment]
다른 스토어로 데이터를 전달한다는게 무슨말씀이신지 감이 안오네요 좀 더 구체적으로 말씀해주실 수 았나요

**Comment by Taeila92** [comment]
리덕스 모듈에서 다른모듈로 데이터를 가져오는거입니다 예를들어서 board 에서 user로 데이터를 가져와서쓸수있는지입니다ㅋㅋ

**Comment by Elli-Jeon** [comment]
저번에 이거 얘기 못 했었는데 어차피 store는 하나니깐 불러와서 쓰는데는 상관없지 않나요?? 어차피 데이터를 fetch만 해온 상황이면
