### ISSUE TITLE
이메일로 회원가입 시 유저 정보

### ISSUE THREAD

**Issue by Park1016** [LM-TeamProject/travel-here#35]
이메일로 회원가입 시에 user_name이 null값으로 들어옵니다.
이메일로 회원가입하면 로그인 정보가 이메일, 패스워드밖에 없어서
user_name이라도 추가하는게 어떨까 하는 의견 내봅니다.
기왕 할 거 프로필 사진도 굳이 마이페이지에가서 수정하지 않고 회원가입때 설정 하면 좋을 것 같은데 어떻게 생각하시나요?

**Comment by Elli-Jeon** [comment]
보통의 경우는 회원가입하면서 프로필 사진을 받지는 않지 않나요..??
인스타그램도 회원가입할 때 프로필 사진을 안 받긴합니다

**Comment by Park1016** [comment]
아 그런가요?? 그럼 사진은 받지않는걸로 합시다!!
