### ISSUE TITLE
post 모달창 라우터 문제

### ISSUE THREAD

**Issue by Park1016** [LM-TeamProject/travel-here#36]
마이페이지에서 내가 쓴 글 등으로 연결하려면 결국 post모달창의 주소가 있어야할 것 같습니다.
쿼리스트링으로 해보려하는데 어떻게 생각하시는지 의견 남겨주세요!

**Comment by Elli-Jeon** [comment]
쿼리스트링으로 하는거는 좋은거 같습니다
보통 /post/?id=111&no=222 이런식이니깐 post의 id가 필요하지 않을까요.??

**Comment by Park1016** [comment]
넵! 한다면 post_id로 하려구요.
