### ISSUE TITLE
WriteModal을 주소로 변경하는 방안

### ISSUE THREAD

**Issue by Park1016** [LM-TeamProject/travel-here#39]
게시글 수정하는 방식을
게시글에서 수정하기를 누르면 WriteModal로 이동하도록 하려고 하는데
그러기 위해선 Write도 modal이 아닌 라우팅이 필요합니다.
이 문제에 대해서 어떻게 생각하시나요??

1. 게시글 수정을 다른 방식으로 하고 write modal은 바꾸지 않는다.
2. 위의 방법대로 수정하고 write modal을 바꾼다.

의견 적어주세요!

**Comment by Elli-Jeon** [comment]
게시글에서 바로 수정은 어떨까요.??

**Comment by Park1016** [comment]
그러면 firestore에 게시글 올리는 코드를 또 써야돼서
writeModal에 있는 코드들과 중복될거같아서
차라리 writeModal에서 다 처리하는게 어떨까 했습니다!

**Comment by Elli-Jeon** [comment]
아 write 틀에다가 바꾸려는 게시글의 내용이 default로 들어가있는 형태... 라고 이해하면 되려나요.?

**Comment by Park1016** [comment]
넵 그런 식으로 생각하고있었어요.
