### ISSUE TITLE
게시글 삭제 관련

### ISSUE THREAD

**Issue by Park1016** [LM-TeamProject/travel-here#40]
게시글 삭제 후 postCard화면이 떴을 때 해당 사항이 바로 반영이 안되고 새로고침을 해야합니다.
상우님이 postCard를 어떻게 렌더링하는지 몰라서 해당문제는 일단 보류해뒀습니다.
나중에 mypage 브랜치 git pull 해서 확인부탁드립니다.

**Comment by Elli-Jeon** [comment]
아무래도 요건 진짜 onSnapShot을 써봐야할 것 같기는 합니다..

https://cloud.google.com/firestore/docs/query-data/listen?hl=ko

한 번 고민해보겠습니다!
