### ISSUE TITLE
사용자 정보 수정 관련

### ISSUE THREAD

**Issue by Park1016** [LM-TeamProject/travel-here#41]
아직 코드를 짜보진 않았지만 문득 생각나서 적어봅니다.
사용자가 프로필 사진을 수정하면 users collection의 정보만 수정되고
나머지는 수정이 안될것같습니다.
예를 들어 post의 프로필 사진, comment의 프로필 사진은 수정이 안됩니다.
제가 초반에 말했던 foreign key와 관련된 문제인 것 같은데
제가 잘못 생각하고있는건지, 아니면 정말 문제인건지
팀원분들 의견 여쭤봅니다.

**Comment by Elli-Jeon** [comment]
좀 더 알아는 봐야겠는데 제 생각으로는 한 번에 바꾸는건 안되고 collection별로 각각 다 바꿔야할거 같습니당

**Comment by Elli-Jeon** [comment]
https://stackoverflow.com/questions/57653308/firestore-transaction-update-multiple-collections-in-a-single-transaction

한 번 참고해보세용

여러 개의 collection을 따로 불러와서 하네요
