### ISSUE TITLE
제가 바라는 개선점

### ISSUE THREAD

**Issue by Park1016** [LM-TeamProject/travel-here#55]
-- 마이페이지 비밀번호 변경 / 회원탈퇴
1. 비밀번호 변경되면 완료됐다는 표시
2. 비밀번호 변경 전에 현재 비밀번호 체크(현재 비밀번호 맞게 누르면 변경할 수 있게끔)
2. 회원탈퇴버튼 누르면 '탈퇴하시겠습니까?' 같은 알림창 띄우기

-- writeModal
1. 이미지 개별 삭제 안됨(이미지 옆에 x아이콘 안먹힘)
2. 상단에 x눌렀다가 다시 들어가면(모달창 나갔다가 다시 들어가면)
   이미지파일 초기화 안되어있음(초기화 되어있는게 낫지 않을까요?)
3. 사진 선택할 때 어떻게 선택하시라는 안내문구가 있으면 좋겠음
   (ctrl누른 상태에서 여러장 선택하기, 드래그해서 여러장 선택하기같은..)
4. writeModal, update 모두 전체적으로 웹사이트의 컨셉과 어울리는 스타일링이 더해지면 좋겠음

**Comment by Taeila92** [comment]
-- writeModal

1번은 해결했습니다
2번은 다시한번 설명해주시면 감사하겠습니다.
3. 추가하면될것같습니다 ㅎㅎ
4. 혹시 예시가 있다면 좋을것같습니다..ㅋㅋㅋㅋ

**Comment by Park1016** [comment]
2. 나갔다 들어와도
![image](https://user-images.githubusercontent.com/76847993/131582585-0258eaa3-ac42-40ed-a02f-b5fb5ce20510.png)

4번은 그냥 디자인적으로 전체적인 css작업을 하면 좋겠어요!

**Comment by Taeila92** [comment]
아 이해했습니다!
