### ISSUE TITLE
client밖의 폴더

### ISSUE THREAD

**Issue by Park1016** [LM-TeamProject/travel-here#57]
저희가 원래 백도 구현하려했지만 결국 client폴더에서 모든것을 구현했으니
client밖의 폴더는 삭제하는게 어떨까요?
read me에 프로젝트 설치 및 실행방법 쓰다보니
이 부분을 정리해야할 것 같아서 이슈에 띄웁니다.

**Comment by Taeila92** [comment]
동의하는부분 입니다.
배포때도 문제가 발생될수 있을 부분이라서 정리해야 될것같습니다.

**Comment by Elli-Jeon** [comment]
시험 삼아서 client 안 파일 다 빼봤는데 정상적으로 잘 되네요 그렇게 해도 될 거 같습니당
